import Beverage from "../../assets/images/product_img1.png"
import Food from "../../assets/images/product_img2.png"


export const brandData = [{
  name: "Brand",
  category: "Food",
  products: 43,
  emissions: 9623.332
},
{
  name: "Brand",
  category: "Drink",
  products: 43,
  emissions: 9623.332
},
{
  name: "Brand",
  category: "Food",
  products: 43,
  emissions: 9623.332
},
{
  name: "Brand",
  category: "Drink",
  products: 33,
  emissions: 963.332
},
{
  name: "Brand",
  category: "Food",
  products: 43,
  emissions: 9623.332
},
{
  name: "Brand",
  category: "Drink",
  products: 43,
  emissions: 9623.332
},
{
  name: "Brand",
  category: "Food",
  products: 43,
  emissions: 9623.332
},
{
  name: "Brand",
  category: "Drink",
  products: 33,
  emissions: 963.332
},
{
  name: "Brand",
  category: "Food",
  products: 43,
  emissions: 9623.332
},
{
  name: "Brand",
  category: "Drink",
  products: 43,
  emissions: 9623.332
},
{
  name: "Brand",
  category: "Food",
  products: 43,
  emissions: 9623.332
},
{
  name: "Brand",
  category: "Drink",
  products: 33,
  emissions: 963.332
}];


export const productDetails = {
  id: 1,
  title: 'Beverage Product',
  status: 'in_review',
  location: 'Brampton Manufacturing and Sales Centre',
  brand: 'Sprite',
  netWeight: 4344,
  weightUnits: 'ml',
  gross: 8743,
  temperature: 'cold',
  reportPeriod: '',
  productionUnits: 343443,
  soldCost: 4232,
  processingFacilitySale: 56,
  density: 8923,
  emission: 32,
  productImage: Beverage,
  ingredients: [
    {
      id: 21,
      name: 'test ingredient 1',
      origin: 'Brazil',
      region: 'SA',
      quantity: 3223,
      unit: 'kg',
      transportation: {
        supplier: {
          id: 'Supplier4',
        },
        temperature: { id: 'Freezed' },
        airTransport: false,
      },
    },
    {
      id: 22,
      name: 'test ingredient 2',
      origin: 'France',
      region: 'EU',
      quantity: 9223,
      unit: 'kg',
      transportation: {
        supplier: {
          id: 'Supplier2',
        },
        temperature: { id: 'Cold' },
        airTransport: true,
      },
    },
    {
      id: 23,
      name: 'test ingredient 3 ',
      origin: 'Canada',
      region: 'NA',
      quantity: 3223,
      unit: 'kg',
      transportation: {
        supplier: {
          id: 'Supplier1',
        },
        temperature: { id: 'Hot' },
        airTransport: false,
      },
    },
    {
      id: 24,
      name: 'test ingredient 4',
      origin: 'USA',
      region: 'NA',
      quantity: 3223,
      unit: 'kg',
      transportation: {
        supplier: {
          id: 'Supplier4',
        },
        temperature: { id: 'Warn' },
        airTransport: true,
      },
    },
  ],
  primaryMaterial: [
    {
      id: 21,
      name: 'test Primary material 1',
      origin: 'Brazil',
      region: 'SA',
      quantity: 3223,
      unit: 'kg',
      transportation: {
        supplier: {
          id: 'Supplier4',
        },
        temperature: { id: 'Freezed' },
        airTransport: false,
      },
    },
    {
      id: 22,
      name: 'test Primary material 2',
      origin: 'France',
      region: 'EU',
      quantity: 9223,
      unit: 'kg',
      transportation: {
        supplier: {
          id: 'Supplier2',
        },
        temperature: { id: 'Cold' },
        airTransport: true,
      },
    },
    {
      id: 24,
      name: 'test Primary material 4',
      origin: 'USA',
      region: 'NA',
      quantity: 3223,
      unit: 'kg',
      transportation: {
        supplier: {
          id: 'Supplier4',
        },
        temperature: { id: 'Warn' },
        airTransport: true,
      },
    },
  ],
  secondaryMaterial: [
    {
      id: 21,
      name: 'test Secondary material 1',
      origin: 'Brazil',
      region: 'SA',
      noOfUnits: 33,
      quantity: 3223,
      unit: 'kg',
      transportation: {
        supplier: {
          id: 'Supplier4',
        },
        temperature: { id: 'Freezed' },
        airTransport: false,
      },
    },
    {
      id: 22,
      name: 'test Secondary material 2',
      origin: 'France',
      region: 'EU',
      noOfUnits: 33,
      quantity: 9223,
      unit: 'kg',
      transportation: {
        supplier: {
          id: 'Supplier2',
        },
        temperature: { id: 'Cold' },
        airTransport: true,
      },
    },
    {
      id: 23,
      name: 'test Secondary material 3 ',
      origin: 'Canada',
      region: 'NA',
      noOfUnits: 33,
      quantity: 3223,
      unit: 'kg',
      transportation: {
        supplier: {
          id: 'Supplier1',
        },
        temperature: { id: 'Hot' },
        airTransport: false,
      },
    },
  ],
  processingFacility: {
    facilityName: 'Facility 2',
    address: 'Brand Manufacturer facility Canada',
    scope1: 2324,
    scope2: 982,
    wasteCF: 323,
  },
  productDistribution: {
    goodsTransported: 42423,
    goodsStored: 323,
    goodsSoldOnline: 2344,
    goodsSoldOffline: 9945,
  },
  endMarketLocation: [
    {
      location: 'Brampton Manufacturing and Sales Centre',
      goodsSent: 443,
      airTransport: false,
      id: 332,
    },
    {
      location: 'Quebec Manufacturing and Sales Centre',
      goodsSent: 9433,
      airTransport: true,
      id: 333,
    },
    {
      location: 'Toronto Manufacturing and Sales Centre',
      goodsSent: 243,
      airTransport: false,
      id: 334,
    },
  ],
};



export const productData = [{
  id:1,
  title: "Beverage Product",
  status: "in_review",
  location: "Brampton Manuf....nd Sales Centre",
  brand: "Sprite",
  emission: 32,
  productImage: Beverage,
},
{
  id:1,
  title: "Beverage Product",
  status: "draft",
  location: "Brampton Manuf....nd Sales Centre",
  brand: "Sprite",
  emission: 82,
  productImage: Beverage,
},
{
  id:1,
  title: "Beverage Product",
  status: "draft",
  location: "Brampton Manuf....nd Sales Centre",
  brand: "Sprite",
  emission: 82,
  productImage: Beverage,
},
{
  id:1,
  title: "Food Product",
  status: "in_review",
  location: "Brampton Manuf....nd Sales Centre",
  brand: "Sprite",
  emission: 29,
  productImage: Food,
},
{
  id:1,
  title: "Beverage Product",
  status: "draft",
  location: "Brampton Manuf....nd Sales Centre",
  brand: "Sprite",
  emission: 82,
  productImage: Beverage,
},
{
  id:1,
  title: "Food Product",
  status: "declined",
  location: "Brampton Manuf....nd Sales Centre",
  brand: "Sprite",
  emission: 29,
  productImage: Food,
},
{
  id:1,
  title: "Beverage Product",
  status: "draft",
  location: "Brampton Manuf....nd Sales Centre",
  brand: "Sprite",
  emission: 82,
  productImage: Beverage,
},
{
  id:1,
  title: "Beverage Product",
  status: "declined",
  location: "Brampton Manuf....nd Sales Centre",
  brand: "Sprite",
  emission: 32,
  productImage: Beverage,
},
{
  id:1,
  title: "Beverage Product",
  status: "draft",
  location: "Brampton Manuf....nd Sales Centre",
  brand: "Sprite",
  emission: 82,
  productImage: Beverage,
},
{
  id:1,
  title: "Food Product",
  status: "declined",
  location: "Brampton Manuf....nd Sales Centre",
  brand: "Sprite",
  emission: 29,
  productImage: Food,
},
{
  id:1,
  title: "Food Product",
  status: "declined",
  location: "Brampton Manuf....nd Sales Centre",
  brand: "Sprite",
  emission: 29,
  productImage: Food,
},
{
  id:1,
  title: "Beverage Product",
  status: "draft",
  location: "Brampton Manuf....nd Sales Centre",
  brand: "Sprite",
  emission: 82,
  productImage: Beverage,
},
{
  id:1,
  title: "Beverage Product",
  status: "verified",
  location: "Brampton Manuf....nd Sales Centre",
  brand: "Sprite",
  emission: 82,
  productImage: Beverage,
},
{
  id:1,
  title: "Food Product",
  status: "declined",
  location: "Brampton Manuf....nd Sales Centre",
  brand: "Sprite",
  emission: 29,
  productImage: Food,
},
{
  id:1,
  title: "Beverage Product",
  status: "verified",
  location: "Brampton Manuf....nd Sales Centre",
  brand: "Sprite",
  emission: 82,
  productImage: Beverage,
},
{
  id:1,
  title: "Beverage Product",
  status: "declined",
  location: "Brampton Manuf....nd Sales Centre",
  brand: "Sprite",
  emission: 32,
  productImage: Beverage,
},
{
  id:1,
  title: "Beverage Product",
  status: "verified",
  location: "Brampton Manuf....nd Sales Centre",
  brand: "Sprite",
  emission: 82,
  productImage: Beverage,
},
{
  id:1,
  title: "Food Product",
  status: "declined",
  location: "Brampton Manuf....nd Sales Centre",
  brand: "Sprite",
  emission: 29,
  productImage: Food,
},
{
  id:1,
  title: "Beverage Product",
  status: "verified",
  location: "Brampton Manuf....nd Sales Centre",
  brand: "Sprite",
  emission: 82,
  productImage: Beverage,
},
{
  id:1,
  title: "Beverage Product",
  status: "verified",
  location: "Brampton Manuf....nd Sales Centre",
  brand: "Sprite",
  emission: 82,
  productImage: Beverage,
},{
  id:1,
  title: "Food Product",
  status: "in_review",
  location: "Brampton Manuf....nd Sales Centre",
  brand: "Sprite",
  emission: 29,
  productImage: Food,
},{
  id:1,
  title: "Food Product",
  status: "in_review",
  location: "Brampton Manuf....nd Sales Centre",
  brand: "Sprite",
  emission: 29,
  productImage: Food,
},{
  id:1,
  title: "Food Product",
  status: "in_review",
  location: "Brampton Manuf....nd Sales Centre",
  brand: "Sprite",
  emission: 29,
  productImage: Food,
},{
  id:1,
  title: "Food Product",
  status: "in_review",
  location: "Brampton Manuf....nd Sales Centre",
  brand: "Sprite",
  emission: 29,
  productImage: Food,
},
{
  id:1,
  title: "Food Product",
  status: "in_review",
  location: "Brampton Manuf....nd Sales Centre",
  brand: "Sprite",
  emission: 29,
  productImage: Food,
},
{
  id:1,
  title: "Food Product",
  status: "in_review",
  location: "Brampton Manuf....nd Sales Centre",
  brand: "Sprite",
  emission: 29,
  productImage: Food,
},
{
  id:1,
  title: "Beverage Product",
  status: "verified",
  location: "Brampton Manuf....nd Sales Centre",
  brand: "Sprite",
  emission: 82,
  productImage: Beverage,
},
{
  id:1,
  title: "Beverage Product",
  status: "draft",
  location: "Brampton Manuf....nd Sales Centre",
  brand: "Sprite",
  emission: 82,
  productImage: Beverage,
},
{
  id:1,
  title: "Food Product",
  status: "in_review",
  location: "Brampton Manuf....nd Sales Centre",
  brand: "Sprite",
  emission: 29,
  productImage: Food,
},
{
  id:1,
  title: "Beverage Product",
  status: "draft",
  location: "Brampton Manuf....nd Sales Centre",
  brand: "Sprite",
  emission: 82,
  productImage: Beverage,
},
{
  id:1,
  title: "Beverage Product",
  status: "in_review",
  location: "Brampton Manuf....nd Sales Centre",
  brand: "Sprite",
  emission: 32,
  productImage: Beverage,
},
{
  id:1,
  title: "Beverage Product",
  status: "draft",
  location: "Brampton Manuf....nd Sales Centre",
  brand: "Sprite",
  emission: 82,
  productImage: Beverage,
},
{
  id:1,
  title: "Food Product",
  status: "in_review",
  location: "Brampton Manuf....nd Sales Centre",
  brand: "Sprite",
  emission: 29,
  productImage: Food,
},
{
  id:1,
  title: "Food Product",
  status: "in_review",
  location: "Brampton Manuf....nd Sales Centre",
  brand: "Sprite",
  emission: 29,
  productImage: Food,
},
{
  id:1,
  title: "Beverage Product",
  status: "draft",
  location: "Brampton Manuf....nd Sales Centre",
  brand: "Sprite",
  emission: 82,
  productImage: Beverage,
},
{
  id:1,
  title: "Beverage Product",
  status: "draft",
  location: "Brampton Manuf....nd Sales Centre",
  brand: "Sprite",
  emission: 82,
  productImage: Beverage,
},
{
  id:1,
  title: "Food Product",
  status: "in_review",
  location: "Brampton Manuf....nd Sales Centre",
  brand: "Sprite",
  emission: 29,
  productImage: Food,
},
{
  id:1,
  title: "Beverage Product",
  status: "draft",
  location: "Brampton Manuf....nd Sales Centre",
  brand: "Sprite",
  emission: 82,
  productImage: Beverage,
},
{
  id:1,
  title: "Beverage Product",
  status: "in_review",
  location: "Brampton Manuf....nd Sales Centre",
  brand: "Sprite",
  emission: 32,
  productImage: Beverage,
},
{
  id:1,
  title: "Beverage Product",
  status: "draft",
  location: "Brampton Manuf....nd Sales Centre",
  brand: "Sprite",
  emission: 82,
  productImage: Beverage,
},
{
  id:1,
  title: "Food Product",
  status: "in_review",
  location: "Brampton Manuf....nd Sales Centre",
  brand: "Sprite",
  emission: 29,
  productImage: Food,
},
{
  id:1,
  title: "Food Product",
  status: "in_review",
  location: "Brampton Manuf....nd Sales Centre",
  brand: "Sprite",
  emission: 29,
  productImage: Food,
},
{
  id:1,
  title: "Beverage Product",
  status: "draft",
  location: "Brampton Manuf....nd Sales Centre",
  brand: "Sprite",
  emission: 82,
  productImage: Beverage,
},
{
  id:1,
  title: "Food Product",
  status: "in_review",
  location: "Brampton Manuf....nd Sales Centre",
  brand: "Sprite",
  emission: 29,
  productImage: Food,
},]
 